package com.chinna.wordToPdf.StringTest1;

public class StringTest1 {

	public static void main(String[] args) {
		 String FETCH_TRADEMARK_DETAILS_QUERY =" SELECT ORDR.TRADEMARK, "+
				" ORDR.TRADEMARK_DESC, "+
				" ORDR.TM_STYLE_ID, "+
				" STLE.CODE_DESC AS TM_STYLE, "+
				" ORDR.TM_TYPE_ID, "+
				" TYP.CODE_DESC AS TM_TYPE, "+
				" ORDR.TRADING_STYLE_ID, "+
				" TSLE.CODE_DESC, "+
				" ORDR.CLASS_TYPE, "+
				" ORDR.HISTORY_OF_OWNERSHIP, "+
				" CITY.CITY_CODE, "+
				" CITY.CITY_NAME AS JURISDICTION, "+
				" ORDR.COLOR, "+
				" ORDR.COLOR_CLAIMED_FLAG, "+
				" ORDR.THREE_DIMENTIONAL_FLAG, "+
				" ORDR.SEARCH_NO, "+
				" TO_CHAR(ORDR.SEARCH_DT,'DD/MM/YYYY') AS SEARCH_DT , "+
				" ORDR.GPA_FLAG, "+
				" ORDR.OFFICIAL_FEE, "+
				" ORDR.TM_IMAGE_NAME, "+
				" ORDR.TM_IMAGE_LOCATION, "+
				" ORDR.REMARKS, "+
				" ORDR.MODE_OF_MAIL_ID, " +
				" ORDR.SPECIAL_INSTRUCTION, "+
				//MAHES : BUG ID : 10372 : START
				" ORDR.CLIENT_REMARKS, USR.USER_NAME AS DATA_VERIFIED_BY, TO_CHAR(ORDR.DATA_VERIFIED_DTM,'DD/MM/YYYY') AS DATA_VERIFIED_DT, "+
				//MAHES : BUG ID : 10372 : END
				//Added by Rajesh on 04-Sep-2012 as part of Bug# 18166 - Start
				" ORDR.NO_OF_MARKS AS NO_OF_MARKS, "+
				//Added by Rajesh on 04-Sep-2012 as part of Bug# 18166 - End
				// added for bug no 27657 
		        " ORDR.LANGUAGE AS LANGUAGE, "+
		        " ORDR.TRANSLATION AS TRANSLATION, "+
		        " ORDR.TRANSLITERATION AS TRANSLITERATION "+		
				" FROM TMS_MAS_ORDER_ENTRY ORDR, "+
				" ACL_MAS_CODE_DTL STLE, "+
				" ACL_MAS_CODE_DTL TYP, "+
				" ACL_MAS_CODE_DTL TSLE, "+
				" CMS_MAS_CITY CITY "+
				" ,ACL_MAS_USER_PROFILE USR "+//MAHES : BUG ID : 10372
				" WHERE (ORDR.TM_STYLE_ID = STLE.CODE_ID AND STLE.CODE_TYPE = 'TRADEMARK_STYLE') "+
				" AND	  (ORDR.TM_TYPE_ID = TYP.CODE_ID AND TYP.CODE_TYPE = 'TRADEMARK_TYPE') "+
				" AND	  (ORDR.TRADING_STYLE_ID = TSLE.CODE_ID AND TSLE.CODE_TYPE = 'TRADING_STYLE') "+
				" AND	  (ORDR.JURISDICTION_CODE = CITY.CITY_CODE AND CITY.JURISDICTION_EXIST_FLAG = 'Y') "+
				" AND ORDR.DATA_VERIFIED_BY = USR.USER_LOGIN_ID(+) "+//MAHES : BUG ID : 10372
				" AND	  ORDR.ORDER_NO = ?1 ";
		 
		 System.out.println(FETCH_TRADEMARK_DETAILS_QUERY);

	}

}
